### ISSUE TITLE
mutipleDefine error when using js api locally

### ISSUE THREAD

**Issue by a13668349935** [Esri/quickstart-map-phonegap#17]
i use some sample code to test phonegap map.
when I use js api on the cdn ,it works fine.
then i build a custom js api using bower,and copy the code in this page:
https://developers.arcgis.com/javascript/3/jshelp/inside_phonegap.html
it return a multipleDefine error.
![image](https://cloud.githubusercontent.com/assets/3089085/17125114/6c87dd52-5323-11e6-926d-46ddb19b06ba.png)

i am using js api 3.17 and phonegap 6.3.0

**Comment by a13668349935** [comment]
could you give me the whole sample project which contains custom build js api.

**Comment by andygup** [comment]
Take a look at the [index_jquerymobilegps_localarcgis.html](https://github.com/Esri/quickstart-map-phonegap/blob/master/index_jquerymobilegps_localarcgis.html) sample. 

Make sure you reference the main [dojo.js file](https://github.com/Esri/quickstart-map-phonegap/blob/master/index_jquerymobilegps_localarcgis.html#L56) pathname correctly.

The order in which theJavaScript libraries are loaded in that sample is important. Changing the order in which libraries are loaded can lead to life-cycle errors.

Let us know if this works?

**Comment by a13668349935** [comment]
i use http://jso.arcgis.com/  to build my js api.and i worked.thanks
